# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
    build_rust_workspace:
        docker:
            - image: circleci/rust:latest
        steps:
            - checkout
            - run:
                name: Check build
                command: cargo check --all

    rust_workspace_clippy:
        docker:
            - image: circleci/rust:latest
        steps:
            - checkout
            - run:
                name: Check clippy
                command: cargo clippy --all

    rust_workspace_fmt:
        docker:
            - image: circleci/rust:latest
        steps:
            - checkout
            - run:
                name: Check formatting
                command: cargo fmt --all -- --check

    rust_workspace_tests:
        docker:
            - image: circleci/rust:latest
        steps:
            - checkout
            - run:
                name: Check tests
                command: cargo test --all

workflows:
    version: 2
    rust:
        jobs:
            - build_rust_workspace
            - rust_workspace_clippy:
                requires:
                    - build_rust_workspace
            - rust_workspace_fmt:
                requires:
                    - build_rust_workspace
            - rust_workspace_tests:
                requires:
                    - build_rust_workspace

